name: SBOM Integrity Signing and Attestation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
################################################################################
# JOB 1
# Build image, push to GHCR, generate SBOM
################################################################################
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      ##########################################################################
      # Install Syft
      ##########################################################################

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

       ##########################################################################
      # Install ORAS
      ##########################################################################

      - name: Install ORAS
        uses: oras-project/setup-oras@v1

      ##########################################################################
      # Login to GHCR
      ##########################################################################

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      ##########################################################################
      # Build image
      ##########################################################################
      - name: Convert image name to lowercase
        id: lowercase
        run: |
          # Convert IMAGE_NAME to lowercase and set it as an output variable
          echo "image=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      ##########################################################################
      # Build image
      ##########################################################################

      - name: Build image
        run: |
          docker build -t $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }} -t $REGISTRY/${{ steps.lowercase.outputs.image }}:latest . 
          #the t flag is used to tag the image with both the commit SHA and the latest tag, allowing for versioning and easy reference to the most recent build.
          #steps.lowercase.outputs.image is used to reference the lowercase image name generated in the previous step, ensuring consistency in naming conventions.
          
      ##########################################################################
      # Push image
      ##########################################################################

      - name: Push image
        run: |
          docker push $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }}
          docker push $REGISTRY/${{ steps.lowercase.outputs.image }}:latest
          #docker push to registry with both commit SHA and latest tag, ensuring the image is available for deployment and version tracking.

      ##########################################################################
      # Capture immutable repository digest
      ##########################################################################

      - name: Capture repository digest
        run: |

          DIGEST=$(docker inspect \
            $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }} \
            --format='{{index .RepoDigests 0}}')

          echo "$DIGEST"

          echo "$DIGEST" > image-digest.txt
          #get the immutable digest of the pushed image using docker inspect and save it to a file named image-digest.txt for later use in the signing and attestation process.

      ##########################################################################
      # Generate SBOM
      ##########################################################################
    
      - name: Generate SBOM - OCI Artifact
        run: |
         syft \
         registry:$REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }} \
         -o cyclonedx-json=sbom.json
        #generate sbom in cyclonedx format using syft for the pushed image and save it to a file named sbom.json for later signing and attestation.
         
      - name: Push SBOM to OCI registry
        run: |
          oras push \
          --artifact-type application/vnd.cyclonedx+json \
          $REGISTRY/${{ steps.lowercase.outputs.image }}-sbom:${{ github.sha }} sbom.json:application/vnd.cyclonedx+json
          #push the generated sbom to the oci registry as an artifact associated with the pushed image, allowing for secure storage and retrieval of the sbom alongside the image.

      ##########################################################################
      # Upload artifacts
      ##########################################################################

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Upload image digest
        uses: actions/upload-artifact@v4
        with:
          name: image-digest
          path: image-digest.txt

          #upload the generated SBOM and image digest as artifacts for use in the subsequent signing and attestation job into paths specified in the workflow, allowing for secure transfer and access between jobs within the same workflow run.

################################################################################
# JOB 2
# Sign SBOM and create attestation
################################################################################

  sign-and-attest:

    needs: build

    runs-on: ubuntu-latest

    steps:

      ##########################################################################
      # Download artifacts
      ##########################################################################

      - name: Download SBOM
        uses: actions/download-artifact@v4
        with:
          name: sbom
          path: .

      - name: Download image digest
        uses: actions/download-artifact@v4
        with:
          name: image-digest
          path: .

          #download the sbom and image digest artifacts generated in the previous build job, making them available for signing and attestation in the current job.

      ##########################################################################
      # Install Cosign
      ##########################################################################

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      ##########################################################################
      # Login to GHCR
      ##########################################################################

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

          #log into the GitHub Container Registry (GHCR) using the provided credentials, enabling secure access for signing and attestation operations.

      ##########################################################################
      # Sign SBOM
      ##########################################################################

      - name: Sign SBOM
        run: |

          cosign sign-blob \
            --yes \
            --output-signature sbom.json.sig \
            --output-certificate sbom.json.pem \
            sbom.json

            #cosign sign-blob is used to sign the SBOM file (sbom.json) and generate a signature file (sbom.json.sig) and a certificate file (sbom.json.pem) for verification purposes. The --yes flag automatically confirms any prompts during the signing process.
            #signature file (sbom.json.sig) contains the cryptographic signature of the SBOM, while the certificate file (sbom.json.pem) contains the public key and metadata needed to verify the signature.
            #this is keyless signing, meaning it does not require a pre-existing private key, and instead uses ephemeral keys generated during the signing process.
            

      ##########################################################################
      # Verify SBOM signature
      ##########################################################################

      - name: Verify SBOM signature
        run: |

          cosign verify-blob \
            --signature sbom.json.sig \
            --certificate sbom.json.pem \
            --certificate-identity "https://github.com/Mikeyogada/SBOM/.github/workflows/sbom-integrity.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            sbom.json
            #this enables keyless verification of the SBOM signature using the certificate generated during signing. It checks that the certificate's identity and OIDC issuer match the expected values, ensuring that the signature is valid and was created by a trusted source.

      ##########################################################################
      # Read repository digest
      ##########################################################################

      - name: Read repository digest
        id: digest
        run: |

          DIGEST=$(cat image-digest.txt)

          echo "digest=$DIGEST" >> $GITHUB_OUTPUT #this echo command set the image digets as variable for GITHUB_OUTPUT to be used in the next steps of the workflow, allowing for easy reference and access to the immutable digest of the pushed image.

      ##########################################################################
      # Create SBOM attestation
      ##########################################################################

      - name: Create SBOM attestation
        run: |

          cosign attest \
            --yes \
            --predicate sbom.json \
            --type cyclonedx \
            ${{ steps.digest.outputs.digest }}

      ##########################################################################
      # Verify attestation
      ##########################################################################

      - name: Verify attestation
        run: |

          cosign verify-attestation \
            --type cyclonedx \
            --certificate-identity "https://github.com/Mikeyogada/SBOM/.github/workflows/sbom-integrity.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            ${{ steps.digest.outputs.digest }}

#summary of the code:
  #This GitHub Actions workflow is designed to ensure the integrity of a software bill of materials (SBOM) for a Docker image. It consists of two main jobs: "build" and "sign-and-attest".
  #In the "build" job, the workflow checks out the repository, installs Syft (a tool for generating SBOMs), logs into GitHub Container Registry (GHCR), builds a Docker image, pushes it to GHCR, captures the image's immutable digest, generates an SBOM in CycloneDX format, and uploads the SBOM and image digest as artifacts.
  #in the "sign-and-attest" job, the workflow downloads the SBOM and image digest artifacts, installs Cosign (a tool for signing and verifying container images), logs into GHCR, signs the SBOM, verifies the signature, reads the repository digest, creates an attestation for the SBOM, and verifies the attestation. The workflow ensures that the SBOM is securely signed and can be verified for authenticity and integrity.