name: sbom sign & verification gate

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

permissions: 
    contents: read # This permission allows the workflow to read the contents of the repository, which is necessary for accessing the SBOM files and other relevant data.
    id-token: write # This permission allows the workflow to create and sign ID tokens, which are necessary for authentication and authorization purposes.
    attestations: write # This permission allows the workflow to create and manage attestations, which are necessary for verifying the integrity and authenticity of the SBOM files.

jobs:
    sbom-sign:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install Syft CLI
              uses: anchore/sbom-action/download-syft@v0

            - name: Generate SBOM
              run: |
                  syft dir:. -o cyclonedx-json=sbom-image.json

            - name: Install Cosign CLI
              uses: sigstore/cosign-installer@v3

            - name: Sign SBOM (keyless)
              run: |
                  cosign sign-blob --yes --output-signature sbom.json.sig --output-certificate sbom.json.pem sbom-image.json
              # cosign - used for signing and verifying container iamges and other artifacts
              # sign-blob - used for signing arbitrary files, in this case the SBOM file
              # --yes - automatically confirm any prompts during the signing process
              # --output-signature - specify the output file for the signature, which contains the digital signature of the SBOM file
              # --output-certificate - specify the output file for the certificate, which contains the public key and other metadata about the signature
              # output-certificate - this is used to store the certificate that can be used for verifying the signature later, it contains the public key and other metadata about the signature
              #difference btn output-signature and output-certificate is that the signature file contains the actual digital signature, while the certificate file contains the public key and other metadata that can be used to verify the signature

            - name: verify SBOm signature
              run: |
                  cosign verify-blob --certificate sbom.json.pem --signature sbom.json.sig --certificate-identity-regexp "https://github.com/Mikeyogada/SCA_labs/.github/workflows/*" --certificate-oidc-issuer "https://token.actions.githubusercontent.com" sbom-image.json
              # cosign - used for signing and verifying container iamges and other artifacts
              # verify-blob - used for verifying the signature of arbitrary files, in this case the SBOM file
              # --certificate - specify the certificate file that contains the public key and metadata for verification
              # --signature - specify the signature file that contains the digital signature to be verified
              # sbom-image.json - this is the original SBOM file that was signed, it is used as the input for verification to ensure that the signature matches the contents of this file
              # --certificate-identity-regexp - this option is used to specify a regular expression that matches the expected identity of the signer, in this case it is set to match any workflow in the specified repository    

            - name: Upload SBOM and signature as artifacts #upload SBOM, signature and certificate files as artifacts of the workflow, this allows you to download and inspect these files after the workflow runs
              uses: actions/upload-artifact@v4
              with:
                  name: sbom-artifacts #name of the artifact, this will be used to identify the artifact when downloading it later
                  path: |
                      sbom-image.json #upload the generated SBOM file as an artifact of the workflow, this allows you to download and inspect the SBOM file after the workflow runs
                      sbom.json.sig #upload the signature file as an artifact of the workflow, this allows you to download and inspect the signature file after the workflow runs
                      sbom.json.pem #upload the certificate file as an artifact of the workflow, this allows you to download and inspect the certificate file after the workflow runs
